version: '3.8'

services:
  php:
    build: .
    container_name: aquaswift
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: NIs@0509
      MYSQL_DATABASE: aquaswift
      MYSQL_USER: aquauser
      MYSQL_PASSWORD: aquapassword
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
